clc;

% Get current directory
current_dir = pwd;

% Get base_dir
file_path = mfilename('fullpath');
file_sep_index = find(file_path == '/');
base_dir = file_path(1:file_sep_index(end));
cd(base_dir)

mex interface/simulation_engine_mex.cpp     ...
    simulation_engine/Mass.cpp              ...
    simulation_engine/Population.cpp        ...
    simulation_engine/Mass_CA1_Lumped.cpp   ...
    simulation_engine/Mass_CA3_Lumped.cpp   ...
    simulation_engine/Mass_HPC_Lumped.cpp   ...
    simulation_engine/Model.cpp             ...
    simulation_engine/NoiseGenerator.cpp    ...
    simulation_engine/Sigma.cpp             ...
    simulation_engine/Stimulator.cpp        ...;

cd(current_dir)

synaptic_gain 				= [3.5 20 10];
synaptic_time_constants 	= [100 30 350];
internal_connectivities 	= [135 108 33.75 33.75 40.5 13.5 108];
mass_connectivities 		= [135 135 55 .16 .16 4];
stimulation_parameters		= [.001 110 1];
simulation_parameters 		= [1.2 3051];

simulation_engine_mex(synaptic_gain, synaptic_time_constants        ...
                   , internal_connectivities, mass_connectivities   ...
                   , stimulation_parameters, simulation_parameters  ...
                   );
    
lfp = csvread('data/example2.csv');
    