mex simulation_engine/Mass.cpp ...
    simulation_engine/Mass_CA1_Lumped.cpp ...
    simulation_engine/Mass_CA3_Lumped.cpp ...
    simulation_engine/Mass_HPC_Lumped.cpp ...
    simulation_engine/Model.cpp ...
    simulation_engine/Noise_Generator.cpp ...
    simulation_engine/Sigma.cpp ...
    simulation_engine/Stimulator.cpp ...
    